name: p_f_e_project
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  
  google_maps_flutter: ^2.2.0
  location: ^8.0.0
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: ^1.19.0
  flutter_animate: ^4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  intl: 0.19.0
  json_path: ^0.7.5
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: ^6.1.2


  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.2
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.0
  url_launcher_windows: ^3.1.4
  pdf: ^3.10.4
  excel: ^4.0.6
  logger: ^2.0.2

  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_ui_auth: ^1.16.1
  firebase_auth_web: ^5.14.0
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  translator: ^1.0.0


  

firebase_database: ^10.0.0 # Ajoute cette ligne
provider: ^6.0.3
dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.10

flutter:
  generate: true
  uses-material-design: true

  assets:
  - lib/l10n/
