// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIuSPXFZhxXrQWHPYr32s3WeTnkqsSpg',
    appId: '1:633918911980:web:96af7f1c4c9710e2303cc9',
    messagingSenderId: '633918911980',
    projectId: 'pfe-project-61a90',
    authDomain: 'pfe-project-61a90.firebaseapp.com',
    storageBucket: 'pfe-project-61a90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhU6_2eMqpO2vg0XTQy_9DRmc37yYj1V0',
    appId: '1:633918911980:android:17a86114914a66a0303cc9',
    messagingSenderId: '633918911980',
    projectId: 'pfe-project-61a90',
    storageBucket: 'pfe-project-61a90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCx243UZUkIc2inDcsiFiaCAS_gSMj82k',
    appId: '1:633918911980:ios:74a4a3a62303603d303cc9',
    messagingSenderId: '633918911980',
    projectId: 'pfe-project-61a90',
    storageBucket: 'pfe-project-61a90.firebasestorage.app',
    iosBundleId: 'com.example.pfeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCx243UZUkIc2inDcsiFiaCAS_gSMj82k',
    appId: '1:633918911980:ios:b50aed1b3a7121c6303cc9',
    messagingSenderId: '633918911980',
    projectId: 'pfe-project-61a90',
    storageBucket: 'pfe-project-61a90.firebasestorage.app',
    iosBundleId: 'com.appschool.pfeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNIuSPXFZhxXrQWHPYr32s3WeTnkqsSpg',
    appId: '1:633918911980:web:62bbe9d7a4a26847303cc9',
    messagingSenderId: '633918911980',
    projectId: 'pfe-project-61a90',
    authDomain: 'pfe-project-61a90.firebaseapp.com',
    storageBucket: 'pfe-project-61a90.firebasestorage.app',
  );
}
